### ISSUE TITLE
CMD Log errors

### ISSUE THREAD

**Issue by ccgguy** [NikitaCern/TaleSpire_Generator#6]
C:\Users\Noble\Documents\GitHub\TaleSpire_Generator>python -m unittest

Asset: ....
AssetManager: EEEE
Config: .
Encode/Decode: .
Generate (last one takes ~30s, be patient!): E
Prop: ..
Quad: ....
Settings: ...
Tiles: ..
======================================================================
ERROR: test_addCustomAsset (test.test_assetManager.TestAssetManager)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\Noble\Documents\GitHub\TaleSpire_Generator\test\test_assetManager.py", line 37, in test_addCustomAsset
    customAssetUUID = AssetManager.addCustomAsset(
  File "C:\Users\Noble\Documents\GitHub\TaleSpire_Generator\objects\assetManager.py", line 60, in addCustomAsset
    customAsset = CustomAsset({
  File "C:\Users\Noble\Documents\GitHub\TaleSpire_Generator\objects\customAsset.py", line 30, in __init__
    self.determineSize()
  File "C:\Users\Noble\Documents\GitHub\TaleSpire_Generator\objects\customAsset.py", line 46, in determineSize
    asset = objects.assetManager.AssetManager.getAsset(uuid)
  File "C:\Users\Noble\Documents\GitHub\TaleSpire_Generator\objects\assetManager.py", line 32, in getAsset
    object = database.fetchall(Asset.SqlGetAsset(str(uuid).lower()))
  File "C:\Users\Noble\Documents\GitHub\TaleSpire_Generator\database\database.py", line 70, in fetchall
    self.cursor.execute(query)
sqlite3.OperationalError: no such table: Assets

======================================================================
ERROR: test_getAsset (test.test_assetManager.TestAssetManager)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\Noble\Documents\GitHub\TaleSpire_Generator\test\test_assetManager.py", line 26, in test_getAsset
    object = AssetManager.getAsset("32cfd208-c363-4434-b817-8ba59faeed17")
  File "C:\Users\Noble\Documents\GitHub\TaleSpire_Generator\objects\assetManager.py", line 32, in getAsset
    object = database.fetchall(Asset.SqlGetAsset(str(uuid).lower()))
  File "C:\Users\Noble\Documents\GitHub\TaleSpire_Generator\database\database.py", line 70, in fetchall
    self.cursor.execute(query)
sqlite3.OperationalError: no such table: Assets

======================================================================
ERROR: test_getCustomAsset (test.test_assetManager.TestAssetManager)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\Noble\Documents\GitHub\TaleSpire_Generator\test\test_assetManager.py", line 64, in test_getCustomAsset
    customAssetUUID = AssetManager.addCustomAsset(
  File "C:\Users\Noble\Documents\GitHub\TaleSpire_Generator\objects\assetManager.py", line 60, in addCustomAsset
    customAsset = CustomAsset({
  File "C:\Users\Noble\Documents\GitHub\TaleSpire_Generator\objects\customAsset.py", line 30, in __init__
    self.determineSize()
  File "C:\Users\Noble\Documents\GitHub\TaleSpire_Generator\objects\customAsset.py", line 46, in determineSize
    asset = objects.assetManager.AssetManager.getAsset(uuid)
  File "C:\Users\Noble\Documents\GitHub\TaleSpire_Generator\objects\assetManager.py", line 32, in getAsset
    object = database.fetchall(Asset.SqlGetAsset(str(uuid).lower()))
  File "C:\Users\Noble\Documents\GitHub\TaleSpire_Generator\database\database.py", line 70, in fetchall
    self.cursor.execute(query)
sqlite3.OperationalError: no such table: Assets

======================================================================
ERROR: test_removeAsset (test.test_assetManager.TestAssetManager)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\Noble\Documents\GitHub\TaleSpire_Generator\test\test_assetManager.py", line 90, in test_removeAsset
    customAssetUUID = AssetManager.addCustomAsset(
  File "C:\Users\Noble\Documents\GitHub\TaleSpire_Generator\objects\assetManager.py", line 60, in addCustomAsset
    customAsset = CustomAsset({
  File "C:\Users\Noble\Documents\GitHub\TaleSpire_Generator\objects\customAsset.py", line 30, in __init__
    self.determineSize()
  File "C:\Users\Noble\Documents\GitHub\TaleSpire_Generator\objects\customAsset.py", line 46, in determineSize
    asset = objects.assetManager.AssetManager.getAsset(uuid)
  File "C:\Users\Noble\Documents\GitHub\TaleSpire_Generator\objects\assetManager.py", line 32, in getAsset
    object = database.fetchall(Asset.SqlGetAsset(str(uuid).lower()))
  File "C:\Users\Noble\Documents\GitHub\TaleSpire_Generator\database\database.py", line 70, in fetchall
    self.cursor.execute(query)
sqlite3.OperationalError: no such table: Assets

======================================================================
ERROR: setUpClass (test.test_generator.TestGenerator)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\Noble\Documents\GitHub\TaleSpire_Generator\test\test_generator.py", line 19, in setUpClass
    "Tree_4": AssetManager.addCustomAsset(
  File "C:\Users\Noble\Documents\GitHub\TaleSpire_Generator\objects\assetManager.py", line 60, in addCustomAsset
    customAsset = CustomAsset({
  File "C:\Users\Noble\Documents\GitHub\TaleSpire_Generator\objects\customAsset.py", line 30, in __init__
    self.determineSize()
  File "C:\Users\Noble\Documents\GitHub\TaleSpire_Generator\objects\customAsset.py", line 46, in determineSize
    asset = objects.assetManager.AssetManager.getAsset(uuid)
  File "C:\Users\Noble\Documents\GitHub\TaleSpire_Generator\objects\assetManager.py", line 32, in getAsset
    object = database.fetchall(Asset.SqlGetAsset(str(uuid).lower()))
  File "C:\Users\Noble\Documents\GitHub\TaleSpire_Generator\database\database.py", line 70, in fetchall
    self.cursor.execute(query)
sqlite3.OperationalError: no such table: Assets

----------------------------------------------------------------------
Ran 21 tests in 0.027s

FAILED (errors=5)

C:\Users\Noble\Documents\GitHub\TaleSpire_Generator>

**Comment by NikitaCern** [comment]
What is your config.ini file contents?

**Comment by ccgguy** [comment]
[TaleSpire_Generator.zip](https://github.com/NikitaCern/TaleSpire_Generator/files/7850401/TaleSpire_Generator.zip)
